version: '3'
services:
  pgdb:
    image: "postgres"
    container_name: "pgdb"
    env_file:
      - .env
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - ./data:/var/lib/postgresql/data